version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE},
      POSTGRES_USER: ${POSTGRES_USER},
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD},
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

volumes:
  db-data:
