version: '3.9'
services:
  postgres:
    container_name: pg_db
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: linkedin
      POSTGRES_USER: linkedin
      POSTGRES_PASSWORD: linkedin
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@mail.ru
      PGADMIN_DEFAULT_PASSWORD: noemail@mail.ru
    ports:
      - '5050:80'
